### ISSUE TITLE
Wrong document path sent to GA

### ISSUE THREAD

**Issue by manetrejo** [TriPSs/react-tag-manager#3]
Hi, 
After I installed the new version an extrange behavior started: every time I go to a route different to the root, a weird document path (dp property) is sent to GA and overriding the correct one.

Step #1, navigating http://mydomain.com/
Query string sent to GA:
dl: http://mydomain.com/ (ok!)
[NO dp property is sent]

Step #2 routing to "steptwo" after user interaction:
Query string sent to GA:
dl | http://mydomain.com/steptwo (ok!)
dp | https://mydomain.com/stepfour (wtf?!)

Step #2 routing to "stepthree" after user interaction:
Query string sent to GA:
dl | http://mydomain.com/stepthree (ok!)
dp | https://mydomain.com/stepfour (wtf?!!!!)

...

The result of this behavior, is that GA is tracking only / and /stepfour.

I can't understand why is overriding the document location with an aleatory document path. 
Hint #1: "stepfour" it's a valid path. 
Hint #2: Even in a develpment environment "dp" takes the full public location (mydomain instead of localhost:3000).
Hint #3: I've tried forcing the 'settings.pageview.locationProp' value but page breaks with the error 'Invariant failed: You should not use <Route> outside a <Router>'.

Any ideas??

**Comment by TriPSs** [comment]
Hi, is it possible that you create a example repo with the bug?

**Comment by manetrejo** [comment]
Hi, thanks. Yes I will try to isolate the issue into a new project.
Meanwhile, does anyone have an example of the use of settings.pageview.locationProp in a React app that uses BrowserRouter?
Thanks

**Comment by manetrejo** [comment]
I close the issue. The problem was caused by an incorrect configuration in GTM.
